version: '3.8'
services:
  app:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - chromadb
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM_MODEL=${LLM_MODEL}
      - CHROMADB_HOST=${CHROMADB_HOST}
      - CHROMADB_PORT=${CHROMADB_PORT}
      - PORT=${PORT}
      - PDF_FILE_LOCATION=${PDF_FILE_LOCATION}
    networks:
      - app_network
    restart: always

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8001"
    volumes:
      - ./data:/data
    networks:
      - app_network
    restart: always

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    volumes:
      - .:/root/.ollama
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
